# Generated by Django 5.2.12 on 2026-06-17 09:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_user_assigned_club_user_wants_club_membership_and_more'),
        ('messenger', '0008_clubimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='requested_club',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requested_members', to='messenger.chatroom', verbose_name='희망 클럽'),
        ),
    ]
