# Generated by Django 5.2.12 on 2026-05-18 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notices', '0011_history_detail'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marquee_enabled', models.BooleanField(default=True, verbose_name='유관기관 스크롤')),
            ],
            options={
                'verbose_name': '사이트 설정',
                'verbose_name_plural': '사이트 설정',
            },
        ),
    ]
